name: cron

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  enantiom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g enantiom
      - run: enantiom -c enantiom.config.json -vv
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
