name: cron

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  enantiom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y fontconfig fonts-noto-cjk && fc-cache -fv
      - run: |
          curl -L https://github.com/airtoxin/surugaya-sentinel/tarball/gh-pages > source.tar.gz
          tar -xzf source.tar.gz
          mv airtoxin-surugaya-sentinel-* dist
      - run: yarn
      - run: yarn start
      - name: Deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
